version: '3'
services:
    nginx:
        build:
            dockerfile: ./docker/nginx.Dockerfile
            context: .
        image: rodrigosqr/nginx
        container_name: nginx
        ports:
            - "8082:80"
        networks: 
            - iftm-network
        depends_on: 
            - "springboot1"
            - "springboot2"
            - "springboot3"

    mysqldb:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=portalferias
            - MYSQL_PASSWORD=root
        networks: 
            - iftm-network
        ports:
            - 3306:3306

    springboot1:
        build:
            dockerfile: ./docker/springboot.Dockerfile
            context: .
        image: rodrigosqr/springboot
        container_name: springboot-1
        ports:
            - "8081:8081"
        networks: 
            - iftm-network
        depends_on:
            - "mysqldb"
        environment:
            - JDBC_DATABASE_URL=jdbc:mysql://mysqldb:3306/portalferias?createDatabaseIfNotExist=true&useSSL=false
            - JDBC_DATABASE_USERNAME=root
            - JDBC_DATABASE_PASSWORD=root

    springboot2:
        build:
            dockerfile: ./docker/springboot.Dockerfile
            context: .
        image: rodrigosqr/springboot
        container_name: springboot-2
        ports:
            - "8081:8081"
        networks: 
            - iftm-network
        depends_on:
            - "mysqldb"
        environment:
            - JDBC_DATABASE_URL=jdbc:mysql://mysqldb:3306/portalferias?createDatabaseIfNotExist=true&useSSL=false
            - JDBC_DATABASE_USERNAME=root
            - JDBC_DATABASE_PASSWORD=root

    springboot3:
        build:
            dockerfile: ./docker/springboot.Dockerfile
            context: .
        image: rodrigosqr/springboot
        container_name: springboot-3
        ports:
            - "8081:8081"
        networks: 
            - iftm-network
        depends_on:
            - "mysqldb"
        environment:
            - JDBC_DATABASE_URL=jdbc:mysql://mysqldb:3306/portalferias?createDatabaseIfNotExist=true&useSSL=false
            - JDBC_DATABASE_USERNAME=root
            - JDBC_DATABASE_PASSWORD=root

networks: 
    iftm-network:
        driver: bridge