version: '3'
services:
    nginx:
        build:
            dockerfile: ./docker/nginx.Dockerfile
            context: .
        image: rodrigosqr/nginx
        container_name: nginx
        ports:
            - "80:80"
        networks: 
            - iftm-network
        depends_on: 
            - "springboot1"
            - "springboot2"
            - "springboot3"

    postgresdb:
        image: sameersbn/postgresql:9.6-2
        container_name: postgresdb
        environment:
            - DB_NAME=portalferias
            - DB_USER=user
            - DB_PASS=user

        networks: 
            - iftm-network
        ports:
            - "5432:5432"

    springboot1:
        build:
            dockerfile: ./docker/springboot.Dockerfile
            context: .
        image: rodrigosqr/springboot
        container_name: springboot-1
        ports:
            - "8081"
        networks: 
            - iftm-network
        environment:
            - JDBC_DATABASE_URL=jdbc:postgresql://postgresdb:5432/portalferias
            - JDBC_DATABASE_USERNAME=user
            - JDBC_DATABASE_PASSWORD=user
            - FLYWAY_ENABLE=true
        depends_on:
            - "postgresdb"

    springboot2:
        build:
            dockerfile: ./docker/springboot.Dockerfile
            context: .
        image: rodrigosqr/springboot
        container_name: springboot-2
        ports:
            - "8081"
        networks: 
            - iftm-network
        environment:
            - JDBC_DATABASE_URL=jdbc:postgresql://postgresdb:5432/portalferias
            - JDBC_DATABASE_USERNAME=user
            - JDBC_DATABASE_PASSWORD=user
            - FLYWAY_ENABLE=false
        depends_on:
            - "postgresdb"


    springboot3:
        build:
            dockerfile: ./docker/springboot.Dockerfile
            context: .
        image: rodrigosqr/springboot
        container_name: springboot-3
        ports:
            - "8081"
        networks: 
            - iftm-network
        environment:
            - JDBC_DATABASE_URL=jdbc:postgresql://postgresdb:5432/portalferias
            - JDBC_DATABASE_USERNAME=user
            - JDBC_DATABASE_PASSWORD=user
            - FLYWAY_ENABLE=false
        depends_on:
            - "postgresdb"

networks: 
    iftm-network:
        driver: bridge
