name: Docker CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          
#       - name: Setup Gradle
#         uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: |
          mvn clean package --file pom.xml

#       - name: Execute Gradle build
#         run: |
#           chmod +x ./gradlew
#           ./gradlew bootJar

      - name: Copy Jar file
        run: mv portalferias/target/$(ls portalferias/target) docker/app/portalferias.jar

      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: docker/app/portalferias.jar
  
  build-image:

    runs-on: ubuntu-latest
    needs: build

    steps:
      
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: jar-file
          path: docker/app/portalferias.jar

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file docker/springboot.Dockerfile --tag springboot:$(date +%s)
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
      
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
      
# #       - name: Login to Docker Hub
# #         uses: docker/login-action@v2
# #         with:
# #           username: ${{ secrets.DOCKERHUB_USERNAME }}
# #           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Set env
#         run: echo "DATE=$(date +%s)" >> $GITHUB_ENV
      
#       - name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           push: true
#           tags: thearaseng/dockerized-spring-boot-app:${{ env.DATE }}
