name: Docker CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Execute Gradle build
        run: |
          mvn clean install -f portalferias/pom.xml -DskipTests=true

      - name: Copy Jar file
        run: mv portalferias/target/portalferias.jar app.jar

      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: app.jar
  
  build-image:

    runs-on: ubuntu-latest
    needs: build

    steps:
      
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: jar-file
          path: app.jar

      - name: Build the Docker image
        run: docker build . --file docker/springboot.Dockerfile --tag springboot:$(date +%s)
